### ISSUE TITLE
Contents of xjtuacm.com/about

### ISSUE THREAD

**Issue by HoboChen** [xjtuacm/board#11]
I suggest not to put the #1 teams into about page.
As:

1. member of first team may vary in one year, e.g. there were different members of `peach` when they won the gold medal
2. it is hard to say which team is the first team, e.g. in 2017 `speakstudystaysing` win the most gold medals but the `setbit` ran into the wf
3. most importantly, i can not see the value of showing the first team members to public; we do have a honor record in http://board.xjtuacm.com/honor/

**Comment by lzy960601** [comment]
1. I agree that there were different members of `peach`, and feel sorry about it. You can put all `peach` members on it if you want.
2. Since 2017, the Captain of XJTUACM will be in the first team. I think one of the best ACMers can be the captain, because only if you are better than others, you can lead XJTUACM. As you said, in 2017, `SpeakStudyStaySing` won the most gold medals and `bitset` ran into wf. But we all admit that the first team of XJTUACM is `SpeakStudyStaySing` in 2017. And in 2018, the captain Cong Ding's team `setbit` will be the first team.
3. As the first team of XJTUACM, we should do more contributions in and out of ACM competition. For example, the first team will choose the problems for others' trainning, the first team will make sure that XJTU have enough seats on regionals, the first team will teach ACM lessons and bring us practice, etc.. So I think it's important to show the first team members to public, since they not only being the first team of XJTUACM, but also standing for XJTUACM and being the idols of who wants to participate in ACM.

**Comment by HoboChen** [comment]
As you wish.
